spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
flashback-api.cors.enabled=true
spring.servlet.multipart.location=/var/electricowl.ovh/flashback/business/tmp
flashback-api.uploads.location=/srv/electricowl.ovh/flashback/www/movies-posters
logging.level.console=
logging.level.root=INFO

